INSERT INTO RESTAURANT (ID,ADDRESS,NAME,CUISINE_TYPE) VALUES(1,'Niederdorfstrasse 80, 8001 Zürich, Schweiz','La Pasta','Italian');
INSERT INTO RESTAURANT (ID,ADDRESS,NAME,CUISINE_TYPE) VALUES(2,'Waaggasse 4, 8001 Zürich, Schweiz','Heugümper','Fusion');
INSERT INTO RESTAURANT (ID,ADDRESS,NAME,CUISINE_TYPE) VALUES(3,'Weinbergstrasse 75, 8006 Zürich, Schweiz','Mesa','European');


INSERT INTO DAY (ID,DAY_OF_WEEK,RESTAURANT_ID) VALUES (1,'MONDAY',1);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(1,'11:30','14:00','OPEN',1);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(2,'17:30','22:00','OPEN',1);

INSERT INTO DAY (ID,DAY_OF_WEEK,RESTAURANT_ID) VALUES (2,'TUESDAY',1);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(3,'11:30','14:00','OPEN',2);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(4,'17:30','22:00','OPEN',2);

INSERT INTO DAY (ID,DAY_OF_WEEK,RESTAURANT_ID) VALUES (3,'WEDNESDAY',1);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(5,'11:30','14:00','OPEN',3);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(6,'17:30','22:00','OPEN',3);

INSERT INTO DAY (ID,DAY_OF_WEEK,RESTAURANT_ID) VALUES (4,'THURSDAY',1);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(7,'11:30','14:00','OPEN',4);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(8,'17:30','22:00','OPEN',4);

INSERT INTO DAY (ID,DAY_OF_WEEK,RESTAURANT_ID) VALUES (5,'FRIDAY',1);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(9,'11:30','14:00','OPEN',5);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(10,'17:30','23:00','OPEN',5);

INSERT INTO DAY (ID,DAY_OF_WEEK,RESTAURANT_ID) VALUES (6,'SATURDAY',1);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(11,'11:30','23:00','OPEN',6);

INSERT INTO DAY (ID,DAY_OF_WEEK,RESTAURANT_ID) VALUES (7,'SUNDAY',1);


INSERT INTO DAY (ID,DAY_OF_WEEK,RESTAURANT_ID) VALUES (8,'MONDAY',2);

INSERT INTO DAY (ID,DAY_OF_WEEK,RESTAURANT_ID) VALUES (9,'TUESDAY',2);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(12,'11:30','14:30','OPEN',9);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(13,'18:30','23:00','OPEN',9);

INSERT INTO DAY (ID,DAY_OF_WEEK,RESTAURANT_ID) VALUES (10,'WEDNESDAY',2);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(14,'11:30','14:30','OPEN',10);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(15,'18:30','23:00','OPEN',10);

INSERT INTO DAY (ID,DAY_OF_WEEK,RESTAURANT_ID) VALUES (11,'THURSDAY',2);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(16,'11:30','14:30','OPEN',11);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(17,'18:30','23:00','OPEN',11);

INSERT INTO DAY (ID,DAY_OF_WEEK,RESTAURANT_ID) VALUES (12,'FRIDAY',2);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(18,'11:30','14:30','OPEN',12);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(19,'18:30','23:00','OPEN',12);

INSERT INTO DAY (ID,DAY_OF_WEEK,RESTAURANT_ID) VALUES (13,'SATURDAY',2);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(20,'11:30','14:30','OPEN',13);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(21,'18:30','23:00','OPEN',13);

INSERT INTO DAY (ID,DAY_OF_WEEK,RESTAURANT_ID) VALUES (14,'SUNDAY',2);

INSERT INTO DAY (ID,DAY_OF_WEEK,RESTAURANT_ID) VALUES (15,'MONDAY',3);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(22,'11:30','14:30','OPEN',15);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(23,'18:30','23:00','OPEN',15);

INSERT INTO DAY (ID,DAY_OF_WEEK,RESTAURANT_ID) VALUES (16,'TUESDAY',3);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(24,'11:30','14:30','OPEN',16);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(25,'18:30','23:00','OPEN',16);

INSERT INTO DAY (ID,DAY_OF_WEEK,RESTAURANT_ID) VALUES (17,'WEDNESDAY',3);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(26,'11:30','14:30','OPEN',17);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(27,'18:30','23:00','OPEN',17);

INSERT INTO DAY (ID,DAY_OF_WEEK,RESTAURANT_ID) VALUES (18,'THURSDAY',3);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(28,'11:30','14:30','OPEN',18);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(29,'18:30','23:00','OPEN',18);

INSERT INTO DAY (ID,DAY_OF_WEEK,RESTAURANT_ID) VALUES (19,'FRIDAY',3);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(30,'11:30','14:30','OPEN',19);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(31,'18:30','23:00','OPEN',19);

INSERT INTO DAY (ID,DAY_OF_WEEK,RESTAURANT_ID) VALUES (20,'SATURDAY',3);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(32,'11:30','14:30','OPEN',20);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(33,'18:30','23:00','OPEN',20);

INSERT INTO DAY (ID,DAY_OF_WEEK,RESTAURANT_ID) VALUES (21,'SUNDAY',3);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(34,'11:30','14:30','OPEN',21);
INSERT INTO OPEN_DETAILS (ID,START,END,TYPE,DAY_ID) VALUES(35,'18:30','23:00','OPEN',21);

